version: '3.8'

services:
  apimiddleware:
    build:
      context: .
      dockerfile: Middleware/Dockerfile
    container_name: apiMiddleware
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  